### ISSUE TITLE
Error: Gone (HTTP 410) even after authentification

### ISSUE THREAD

**Issue by 1nefertarip** [RMHogervorst/nsapi#3]
Hi, I have trouble with this package. I keep on having HTTP 410 response even after authentification using Sys.setenv(NSAPIACCOUNT = "email") and Sys.setenv(NSAPIPW = "password!"). It is also confirmed using check_ns_api_keys() function. I also have turn on the subscription to ns-app APIs. I am sure that the password and email is the correct one.

Did I missing something here?

**Comment by RMHogervorst** [comment]
I haven't checked the APIs yet. There might be changes. Thank you for reporting this!

**Comment by RMHogervorst** [comment]
Hi @1nefertarip We have a problem. NS has gone over to new apis. (see also issue #2) I'm afraid nothing of this package works anymore. I have to rewrite the entire package (the endpoints are different now).

Unfortunately I do not have the time to do that now. So I will mark this package as no longer maintained and pull the package from CRAN too. You are of course welcome to fork this package and make it work for you!
